# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &NetworkMobilityOrg
        # NetworkMobilityOrg defines the organization which is used in the sampleconfig
        Name: NetworkMobilityOrgMSP

        # ID to load the MSP definition as
        ID: NetworkMobilityOrgMSP

        MSPDir: ../organizations/peerOrganizations/networkmobility.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('NetworkMobilityOrgMSP.admin', 'NetworkMobilityOrgMSP.peer', 'NetworkMobilityOrgMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('NetworkMobilityOrgMSP.admin', 'NetworkMobilityOrgMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('NetworkMobilityOrgMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('NetworkMobilityOrgMSP.peer')"
