---
name: test-network-networkmobility
version: 1.0.0

placeholders:
  PEER_PORT: ${P0PORT}
  PEER_CERT: ${PEERPEM}
  CA_PORT: ${CAPORT}
  CA_CERT: ${CAPEM}

client:
  organization: NetworkMobilityOrg
  connection:
    timeout:
      peer:
        endorser: '300'

organizations:
  NetworkMobilityOrg:
    mspid: NetworkMobilityOrgMSP
    peers:
      - peer0.networkmobility.example.com
    certificateAuthorities:
      - ca.networkmobility.example.com

peers:
  peer0.networkmobility.example.com:
    url: grpcs://localhost:${PEER_PORT}
    tlsCACerts:
      pem: |
        ${PEER_CERT}
    grpcOptions:
      ssl-target-name-override: peer0.networkmobility.example.com
      hostnameOverride: peer0.networkmobility.example.com

certificateAuthorities:
  ca.networkmobility.example.com:
    url: https://localhost:${CA_PORT}
    caName: ca-networkmobility
    tlsCACerts:
      pem:
        - |
          ${CA_CERT}
    httpOptions:
      verify: false