# SPDX-License-Identifier: Apache-2.0 
version: '2.1'

volumes:
  pgdata:
  walletstore:

networks:
  fabric_test:  # Updated to match existing network name
    name: fabric_test
    external: true

services:

  explorerdb.fabric_test:
    image: ghcr.io/hyperledger-labs/explorer-db:latest
    container_name: explorerdb.fabric_test
    hostname: explorerdb.fabric_test
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - fabric_test

  explorer.fabric_test:
    image: ghcr.io/hyperledger-labs/explorer:latest
    container_name: explorer.fabric_test
    hostname: explorer.fabric_test
    environment:
      - DATABASE_HOST=explorerdb.fabric_test
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=info
      - LOG_LEVEL_DB=info
      - LOG_LEVEL_CONSOLE=debug
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
      - PORT=${PORT:-8080}
    volumes:
      - ${EXPLORER_CONFIG_FILE_PATH}:/opt/explorer/app/platform/fabric/config.json
      - ${EXPLORER_PROFILE_DIR_PATH}:/opt/explorer/app/platform/fabric/connection-profile/security-network.json  # Updated if renamed
      - ${FABRIC_CRYPTO_PATH}:/tmp/crypto
      - walletstore:/opt/explorer/wallet
    ports:
      - ${PORT:-8080}:${PORT:-8080}
    depends_on:
      explorerdb.fabric_test:
        condition: service_healthy
    networks:
      - fabric_test
